### ISSUE TITLE
writeOutputFile generates empty Folders in project root

### ISSUE THREAD

**Issue by stefanzweifel** [tightenco/jigsaw#322] opened 2019-02-20 08:26 UTC
Hi there 👋

This isn't necessarily an issue but more a little annoyance.
When I'm using `$jigsaw->writeOutputFile()` in a listener, Jigsaw creates an empty directory structure in the root of the project.

For example:
- My Jigsaw project is located here: `/Users/stefan/projects/example.org/`
- After running `jigsaw build` a new folder `Users` appears in the root of the project
- The new folder contains empty folders and matches the path of the project (eg. `/Users/stefan/projects/example.org/Users/stefan/projects/example.org/`)

I've seen, that the `GenerateIndex`-example in [tightenco/jigsaw-blog-template](https://github.com/tightenco/jigsaw-blog-template/blob/5a88893ff04db7e57846e3563c70bfcfbdec1cd7/listeners/GenerateIndex.php) uses `file_put_contents` instead of `$jigsaw->writeOutputFile()`. 
Is this on purpose? Or is this just to keep the example as simple as possible?

```php
<?php

namespace App\Listeners;

use TightenCo\Jigsaw\Jigsaw;

class GenerateIndex
{
    public function handle(Jigsaw $jigsaw)
    {
        $data = collect($jigsaw->getCollection('posts')->map(function ($page) use ($jigsaw) {
            return [
                'title' => $page->title,
                'categories' => $page->categories,
                'link' => rightTrimPath($jigsaw->getConfig('baseUrl')) . $page->getPath(),
                'snippet' => $page->getExcerpt(),
            ];
        })->values());

        // Using $jigsaw->writeOutputFile() would create empty folders
        // $jigsaw->writeOutputFile('index.json', json_encode($data));

        file_put_contents($jigsaw->getDestinationPath() . '/index.json', json_encode($data));
    }
}
```

I could pinpoint the cause of this bug to [this line](https://github.com/tightenco/jigsaw/blob/fb9cd18e36ec78a77d6151b37bbc41a6c12f4418/src/File/Filesystem.php#L22) in `TightenCo\Jigsaw\File\Filesystem`.

The value of `$file_path` in my example would be `/Users/stefan/projects/example.org/build_local/index.html`. 
But by calling `trimPath()` the first `/` get's removed (eg. `Users/stefan/projects/example.org/build_local`) and the folder structure get's created in the root of the project.

I guess `trimPath()` is there to fix compatibility issues between Linux, macOS and Windows? So just switching to `rightTrimPath()` would cause issues on Windows machines 🤔 

So my questions are: 

- Would you accept a PR which fixes this behavior?
- In which contexts should `writeOutputFile()` be used?

**Comment by m1guelpf** [comment] 2019-02-21 07:41
OMG this, I've been having this bug for ages but I thought it was caused by my custom parser. Would love a fix for this :)

**Comment by damiani** [comment] 2019-02-21 07:45
We would definitely welcome a PR to fix this, and we should also update the blog template to use `writeOutputFile()`.

**Comment by stefanzweifel** [comment] 2019-02-21 07:48
Great. I will look into it more and send you a PR; hopefully in the next days.

**Closed** 2019-09-26 12:53 UTC
