### ISSUE TITLE
create multi lingual website

### ISSUE THREAD

**Issue by iz5clj** [tightenco/jigsaw#261] opened 2018-08-29 18:02 UTC
Hi.

Some idea on how I can build a static multi lingual website with jigsaw?
The main problem is the menu!
How would it be possible to load the menu in the appropriate language?

Thanks in advance.
Michel.

**Comment by ButGuc** [comment] 2018-08-29 20:04
I solved the problem by using separate build and data source for each language. but this method makes the development process extremely difficult.  I wrote a script to accelerate the process to some extent. but it does not help much.

**Comment by iz5clj** [comment] 2018-08-30 09:17
Thank you for your reply.

**Comment by damiani** [comment] 2018-10-02 12:45
Duplicate of #25

**Closed by damiani** 2018-10-02 12:45 UTC
