### ISSUE TITLE
Collection isn't working

### ISSUE THREAD

**Issue by imam** [tightenco/jigsaw#99] opened 2017-04-24 05:15 UTC
Hello.

The collection isn't working at all. I've tried to add `path` to `posts` in the `collection` array, not working. But the `jigsaw console` do notice the `_posts` folder because it would throw me an error if it isn't there, but it just won't render any item in the folder. What am I did wrong?

![2017-04-24_114849](https://cloud.githubusercontent.com/assets/8213031/25323148/a5d3c374-28e7-11e7-939b-dc4068d6bdeb.png)

The picture note:
1. The left editor is the `1-helloworld.md`
2. The right editor is the `config.php`

**Comment by damiani** [comment] 2017-04-24 14:51
I can't see any issues with your code (although the file `1-helloworld.md` is set to extend the `master` template, so your `post` template won't be used), though it's possible there's some issue relating to running on Windows. Do you get any error message when trying to build the site? 

If you upload a zip of your site, or link to a repo, I can test it out more fully.

**Comment by imam** [comment] 2017-04-25 02:38
There aren't any error, it just won't render the output.

For the repo: https://github.com/imam/imamtech-jigsaw

**Comment by imam** [comment] 2017-04-25 02:47
![2017-04-25_094647](https://cloud.githubusercontent.com/assets/8213031/25366791/39091144-299c-11e7-8ca2-57934999bb50.png)

**Comment by damiani** [comment] 2017-04-25 16:08
Your code builds fine for me when I run it on my mac, but something is causing the collection build to fail silently when I test it on Windows. I'm not certain yet of the cause.

**Comment by damiani** [comment] 2017-04-30 12:28
Actually, scratch that, it's working fine for me on Windows. At least, on Windows running the Ubuntu bash, which it _looks_ like you are running as well? (In my earlier test, I had mistakenly cleared out `config.php` so it had appeared to not work.) So I'm a bit stuck, since I can't reproduce the error when building from your repo.

![imam-test](https://cloud.githubusercontent.com/assets/357312/25564323/da418df8-2d7e-11e7-9714-7503e0934725.png)

**Comment by VictorAvelar** [comment] 2017-05-30 21:49
@imam @damiani Just hit the same problem, everything works fine but it does not generate the output files, the data is parsed because I can loop through the collection as $posts.

Do you manage to solve this?

**Comment by damiani** [comment] 2017-05-30 21:55
I wasn't able to reproduce the issue. Could you post a repo of your code, as well as some details about your setup? Running on Windows, using the Ubuntu bash shell, @imam's code built fine for me. I'd love to give yours a try to see if I can recreate the problem.

**Comment by VictorAvelar** [comment] 2017-05-30 22:05
@damiani Thanks for such a quick answer, this is a [link](https://github.com/VictorAvelar/me-jigsaw) to my project repo, I'm using Windows 7, git bash, jigsaw installed globally and I think that's all.

**Comment by AyubM** [comment] 2017-07-11 05:40
Can confirm it doesn't work using Powershell with the provided jigsaw.bat

I had to run jigsaw through my VM running debian to build successfully

**Comment by garhbod** [comment] 2017-07-21 01:54
I believe I have fixed this bug with the pull request #126

**Comment by cmosguy** [comment] 2017-07-28 12:39
I have confirmed that https://github.com/tightenco/jigsaw/pull/126 fixes the issue.

**Comment by adrianR84** [comment] 2017-07-30 21:01
hello
In regards to this, I am using Windows 10, git bash and it does not generates the output files...

**Comment by damiani** [comment] 2017-07-30 21:07
@adrianR84 Did you apply the fix from #126, and it still didn't work on Windows?

**Comment by adrianR84** [comment] 2017-07-31 07:09
Yes, I did not work. I have tried both, `$parts = preg_split('/[\\/\\\]+/', $this->relativePath());` and `$parts = explode(DIRECTORY_SEPARATOR, $this->relativePath());` .... This code was added to .\vendor\tightenco\jigsaw\src\File\InputFile.php file and after I tried generating the build once again with `./vendor/bin/jigsaw build` command.  Am I doing something wrong ?
Thank you.

**Comment by garhbod** [comment] 2017-08-01 02:55
@adrianR84 you also need the changes to the relativePath method of InputFile. Grab the latest changes from the below link and replace the entire InputFile with it. Also you need to make sure u are running the  `./vendor/bin/jigsaw build` command rather than the global `jigsaw build` . Please let me know your results

https://raw.githubusercontent.com/garhbod/jigsaw/efd36fd0fa7144ed1cd19528db57de2b3f035dd8/src/File/InputFile.php

**Comment by garhbod** [comment] 2017-08-01 02:57
@cmosguy can you please test again with the latest changes mentioned in my previous post

**Comment by adrianR84** [comment] 2017-08-01 06:42
Hello

Considering the file that you have given to me, it is working perfectly. Thank you for your help and quick reply.

**Comment by cmosguy** [comment] 2017-08-01 12:36
@damiani @adrianR84 I have tested the updated and it is working just fine now.  I have tested on my windows 10 system.

Thanks for the updates!

**Comment by damiani** [comment] 2017-08-01 12:40
Excellent, thanks for testing!

**Comment by damiani** [comment] 2017-08-01 13:14
Addressed by https://github.com/tightenco/jigsaw/pull/126

**Closed by damiani** 2017-08-01 13:14 UTC
